# Copyright (c) 2026, ErpGenEx
"""Resolve distinct portal/menu icons per link — not generic link-type icons."""

from __future__ import annotations

import re

_LINK_TYPE_FALLBACK = {
	"Page": "▫️",
	"DocType": "▫️",
	"Report": "▫️",
	"Dashboard": "▫️",
	"Workspace": "▫️",
	"URL": "▫️",
}

# Page name suffix patterns (checked before generic keyword rules).
_PAGE_SUFFIX_ICONS: tuple[tuple[str, str], ...] = (
	("-executive-dashboard", "📊"),
	("-analytics-dashboard", "📈"),
	("-operations-desk", "⚙️"),
	("-finance-desk", "💰"),
	("-customer-portal", "👤"),
	("-client-portal-desk", "👤"),
	("-servicing-portal", "🎧"),
	("-sales-portal", "🛒"),
	("-lawyer-desk", "👨‍⚖️"),
	("-intake-desk", "📥"),
	("-paralegal-desk", "📋"),
	("-secretary-desk", "📅"),
	("-manager-desk", "🏛️"),
	("-guest-pwa", "🧳"),
	("-field-pwa", "📱"),
	("-asset-scan-pwa", "📱"),
	("-van-sales-pwa", "🚐"),
	("-live-asset-tracking", "📡"),
	("-linen-dashboard", "🛏️"),
	("-asset-wizards", "🧙"),
	("-hotel-assets-dashboard", "🏨"),
	("-hospitality-command-center", "🎯"),
	("-global-hospitality-portfolio", "🌍"),
	("-workcenter", "🏢"),
	("-demo-hub", "🧪"),
	("-console", "🖥️"),
	("-signing-agent", "🔐"),
	("-pwa", "📱"),
)

# Token inference — last resort before link-type fallback.
_TOKEN_ICONS: dict[str, str] = {
	"registration": "📥",
	"consultation": "💬",
	"appointment": "📅",
	"attorney": "✍️",
	"hearing": "🏛️",
	"conflict": "⚠️",
	"jurisdiction": "🌍",
	"lawyer": "👨‍⚖️",
	"paralegal": "📋",
	"secretary": "📅",
	"matter": "📜",
	"client": "👥",
	"case": "⚖️",
	"court": "🏛️",
	"document": "📁",
	"task": "✅",
	"invoice": "🧾",
	"payment": "💳",
	"receipt": "🧾",
	"order": "🛒",
	"purchase": "🛒",
	"sales": "🛍️",
	"delivery": "🚚",
	"stock": "📦",
	"warehouse": "🏭",
	"inventory": "📦",
	"batch": "📦",
	"serial": "🔢",
	"employee": "👷",
	"payroll": "💵",
	"leave": "🏖️",
	"attendance": "🕐",
	"recruitment": "➕",
	"applicant": "👤",
	"student": "🎓",
	"teacher": "👩‍🏫",
	"course": "📚",
	"exam": "📝",
	"grade": "📊",
	"patient": "🏥",
	"clinical": "💉",
	"lab": "🧪",
	"prescription": "💊",
	"room": "🚪",
	"bed": "🛏️",
	"booking": "📅",
	"folio": "🧾",
	"housekeeping": "🧹",
	"maintenance": "🔧",
	"inspection": "🔍",
	"workorder": "🔧",
	"asset": "🏢",
	"depreciation": "📉",
	"acquisition": "💵",
	"revaluation": "💹",
	"transfer": "🔄",
	"disposal": "🗑️",
	"project": "📐",
	"contract": "📜",
	"budget": "💰",
	"cost": "💰",
	"commission": "💵",
	"lead": "🎯",
	"reservation": "📅",
	"property": "🏠",
	"unit": "🏢",
	"tenant": "👤",
	"lease": "🔑",
	"mortgage": "🏠",
	"vehicle": "🚗",
	"rental": "🚗",
	"farm": "🌾",
	"crop": "🌾",
	"harvest": "🌾",
	"livestock": "🐄",
	"audit": "🔎",
	"finding": "🔍",
	"evidence": "📎",
	"engagement": "📋",
	"risk": "⚠️",
	"stress": "📉",
	"governance": "🛡️",
	"compliance": "✅",
	"policy": "📜",
	"calibration": "🎯",
	"portfolio": "💼",
	"cluster": "🔗",
	"watchlist": "👁️",
	"default": "⚠️",
	"roll": "📊",
	"collection": "📞",
	"factoring": "📄",
	"submission": "📤",
	"signing": "🔐",
	"authority": "🏛️",
	"settings": "⚙️",
	"profile": "👤",
	"branch": "🏢",
	"office": "🏢",
	"area": "🗺️",
	"practice": "⚖️",
	"firm": "🏛️",
	"ticket": "🎫",
	"sla": "⏱️",
	"timesheet": "🕐",
	"service": "🛎️",
	"menu": "🍽️",
	"recipe": "👨‍🍳",
	"table": "🪑",
	"kitchen": "🍳",
	"nursery": "🌱",
	"child": "👶",
	"parent": "👨‍👩‍👧",
	"enrollment": "📝",
	"attendance": "🕐",
	"rfid": "📡",
	"linen": "🛏️",
	"laundry": "🧺",
	"wizard": "🧙",
	"scan": "📱",
	"tracking": "📡",
	"analytics": "📈",
	"executive": "📊",
	"dashboard": "📊",
	"report": "📊",
	"summary": "📊",
	"register": "📋",
	"ledger": "📒",
	"journal": "📒",
	"account": "🏦",
	"supplier": "🏭",
	"customer": "👤",
	"item": "📦",
	"quotation": "📝",
	"tender": "📋",
	"pos": "🖥️",
	"terminal": "🖥️",
	"recall": "⚠️",
	"cold": "❄️",
	"chain": "❄️",
	"controlled": "🔒",
	"substance": "🔒",
	"ai": "🤖",
	"agent": "🤖",
	"copilot": "🤖",
	"edms": "📁",
	"folder": "📁",
	"workflow": "🔀",
	"integration": "🔗",
	"bridge": "🌉",
	"backup": "💾",
	"academy": "🎓",
	"theme": "🎨",
	"demo": "🧪",
	"saas": "☁️",
	"experience": "✨",
	"intelligence": "🧠",
	"setup": "⚙️",
	"manufacturing": "🏭",
	"bom": "📋",
	"workstation": "🏭",
	"operation": "⚙️",
	"quality": "✅",
	"inspection": "🔍",
	"submittal": "📤",
	"engineering": "📐",
	"riba": "📐",
	"stage": "📐",
	"tourism": "✈️",
	"travel": "✈️",
	"package": "🎁",
	"hotel": "🏨",
	"guest": "🧳",
	"occupancy": "🛏️",
	"pricing": "💲",
	"agriculture": "🌾",
	"restaurant": "🍽️",
	"construction": "🏗️",
	"boq": "📋",
	"variation": "📈",
	"subcontract": "🤝",
	"retention": "🔒",
	"milestone": "🏁",
	"progress": "📈",
	"alm": "🏦",
	"liquidity": "💧",
	"treasury": "🏦",
	"ecl": "📉",
	"ifrs": "📊",
	"calibration": "🎯",
	"backtest": "🧪",
	"validation": "✅",
	"inbox": "📥",
	"outbox": "📤",
	"event": "📣",
	"template": "📄",
	"scenario": "🎭",
	"calc": "🧮",
	"product": "📦",
	"installment": "💳",
	"repayment": "💵",
	"schedule": "📅",
	"parcel": "📦",
	"dispatch": "🚚",
	"receiving": "📥",
	"margin": "📈",
	"profit": "💰",
	"loss": "📉",
	"heatmap": "🌡️",
	"monitor": "👁️",
	"tracker": "📍",
	"reconciliation": "🔄",
	"settlement": "💵",
	"accrual": "📈",
	"roi": "📈",
	"campaign": "📣",
	"reservation": "📅",
	"commission": "💵",
	"opinion": "📝",
	"snapshot": "📸",
	"balance": "⚖️",
	"general": "📒",
	"trial": "⚖️",
	"missing": "❓",
	"warranty": "⏳",
	"forecast": "🔮",
	"health": "❤️",
	"alert": "🔔",
	"failure": "⚠️",
	"movement": "🔄",
	"location": "📍",
	"category": "🏷️",
	"valuation": "💰",
	"nbv": "📊",
	"power": "✍️",
	"company": "🏢",
	"user": "👤",
	"role": "🎭",
	"uom": "📏",
	"bim": "🏗️",
	"hse": "🦺",
	"hazard": "⚠️",
	"ncr": "⏳",
	"ipc": "📜",
	"rfq": "📋",
	"bid": "📋",
	"toll": "🛣️",
	"fleet": "🚗",
	"fuel": "⛽",
	"charging": "⚡",
	"damage": "🚗",
	"vaccination": "💉",
	"plot": "🌾",
	"capa": "✅",
	"deviation": "⚠️",
	"sop": "📜",
	"signature": "✍️",
	"vendor": "✅",
	"equipment": "🔧",
	"zone": "🗺️",
	"route": "🗺️",
	"tender": "📋",
	"regulatory": "✅",
	"drug": "💊",
	"license": "📜",
	"shipment": "📤",
	"sample": "🧪",
	"temperature": "🌡️",
	"excursion": "🌡️",
	"penetration": "🔒",
	"load test": "⚡",
	"diagnostic": "🩺",
	"uniclass": "📚",
	"evm": "📈",
	"fulfillment": "📦",
	"efficiency": "🛣️",
	"utilization": "🚗",
	"card": "📋",
	"nbv": "💰",
	"summary": "🗂️",
}

# Exact link_to (Page / DocType / Report name).
_EXACT_ICONS: dict[str, str] = {
	# Legal — pages
	"legal-workcenter": "⚖️",
	"legal-lawyer-desk": "👨‍⚖️",
	"legal-intake-desk": "📥",
	"legal-paralegal-desk": "📋",
	"legal-secretary-desk": "📅",
	"legal-manager-desk": "🏛️",
	"legal-executive-dashboard": "📊",
	"legal-finance-desk": "💰",
	"legal-analytics-dashboard": "📈",
	"legal-client-portal-desk": "👤",
	# Legal — doctypes
	"Client Registration Request": "📥",
	"Legal Consultation": "💬",
	"Legal Appointment": "📅",
	"Legal Power of Attorney": "✍️",
	"Legal Client": "👥",
	"Legal Matter": "📜",
	"Legal Case": "⚖️",
	"Legal Conflict Check": "⚠️",
	"Legal Hearing": "🏛️",
	"Legal Task": "✅",
	"Legal Document": "📁",
	"Court": "🏛️",
	"Law Firm": "🏛️",
	"Lawyer Profile": "👨‍⚖️",
	"Practice Area": "⚖️",
	"Legal Jurisdiction": "🌍",
	"Legal Branch": "🏢",
	"Legal Office": "🏢",
	"Legal Settings": "⚙️",
	# Fixed assets — pages
	"fixed-assets-workcenter": "🏢",
	"fa-executive-dashboard": "📊",
	"fixed-assets-analytics-dashboard": "📈",
	"fixed-assets-operations-desk": "⚙️",
	"fixed-assets-finance-desk": "💰",
	"fixed-assets-customer-portal": "👤",
	"fa-live-asset-tracking": "📡",
	"fa-asset-scan-pwa": "📱",
	"fa-linen-dashboard": "🛏️",
	"fa-asset-wizards": "🧙",
	"fa-hotel-assets-dashboard": "🏨",
	"fa-hospitality-command-center": "🎯",
	"fa-global-hospitality-portfolio": "🌍",
	# Fixed assets — doctypes & reports (subset — tokens cover rest)
	"Fixed Asset Category": "🏷️",
	"Fixed Asset": "🏢",
	"Fixed Asset Location": "📍",
	"Fixed Asset Acquisition": "💵",
	"Fixed Asset Depreciation Entry": "📉",
	"Fixed Asset Revaluation": "💹",
	"Fixed Asset Transfer": "🔄",
	"Fixed Asset Disposal": "🗑️",
	"Fixed Asset Write-Off": "✂️",
	"Fixed Asset Maintenance": "🔧",
	"Fixed Asset Inspection": "🔍",
	"Fixed Asset Movement Log": "📦",
	"Asset Work Order": "🔧",
	"Asset Failure Event": "⚠️",
	"Asset Alert": "🔔",
	"Asset Lifecycle Wizard Session": "🧙",
	"Hotel Property": "🏨",
	"Hotel Functional Area": "🗺️",
	"Hotel Room": "🚪",
	"Hotel Floor Plan": "🗺️",
	"Hotel Asset Inspection": "🔍",
	"Hotel Asset Transfer": "🔄",
	"Hospitality Audit Event": "📋",
	"RFID Gateway": "📡",
	"RFID Reader": "📶",
	"RFID Scan Log": "📡",
	"Linen Item": "🛏️",
	"Linen Movement": "🔄",
	"Linen Laundry Cycle": "🧺",
	"Linen Issue Batch": "📦",
	"Linen Shortage Alert": "⚠️",
	"Asset Register Report": "📋",
	"Asset Valuation Report": "💰",
	"Fixed Asset Summary": "🗂️",
	"Asset Depreciation Schedule": "📉",
	"Fixed Asset NBV by Category": "💰",
	"Asset Movement Report": "🔄",
	"Replacement Forecast Report": "🔮",
	"Inspection Compliance Report": "✅",
	"Asset Health Report": "❤️",
	"Assets by Room": "🚪",
	"Hotel Assets by Floor": "🏨",
	"Hotel Operational Asset Status": "📊",
	"Hotel Inspection Summary": "🔍",
	"Missing Assets": "❓",
	"Last Seen Assets": "👁️",
	"Unscanned Assets": "📵",
	"Hotel Movement History": "📜",
	"Hotel Asset Depreciation": "📉",
	"Warranty Expiring Assets": "⏳",
	"Missing Linen": "🛏️",
	# Core ERP / finance
	"Journal Entry": "📒",
	"GL Account": "🏦",
	"Sales Invoice": "🧾",
	"Purchase Invoice": "🧾",
	"Payment Entry": "💳",
	"Cost Center": "🏷️",
	"Customer": "👤",
	"Supplier": "🏭",
	"Item": "📦",
	"Stock Entry": "📦",
	"Purchase Order": "🛒",
	"Sales Order": "🛍️",
	"Delivery Note": "🚚",
	"Project": "📐",
	"Task": "✅",
	"Employee": "👷",
	"Leave Application": "🏖️",
	"Salary Slip": "💵",
	"Attendance": "🕐",
	# Healthcare
	"Patient": "🏥",
	"Patient Appointment": "📅",
	"Clinical Procedure": "💉",
	"Lab Test": "🧪",
	"Vital Signs": "❤️",
	# Trading / pharma
	"Batch Recall": "⚠️",
	"Cold Chain Log": "❄️",
	"GDP Audit Trail": "📋",
	"Controlled Substance Log": "🔒",
	# Services
	"Service Ticket": "🎫",
	"Service Contract": "📜",
	"Service Definition": "📋",
	"Service SLA Policy": "⏱️",
	"Service Timesheet": "🕐",
	"Service Invoice": "🧾",
	# Tourism
	"Tourism Booking": "📅",
	"Tourism Hotel": "🏨",
	"Tourism Room Unit": "🚪",
	"Tourism Guest Folio": "🧾",
	"Tourism Housekeeping Task": "🧹",
	# E-invoice / tax
	"E Invoice Submission": "📤",
	"Tax Authority Profile": "🏛️",
	"ZATCA Company Settings": "🇸🇦",
	"eta-einvoice-console": "📤",
	"eta-ereceipt-console": "🧾",
	"zatca-console": "🇸🇦",
	"international-tax-console": "🌐",
	# EDMS / AI
	"EDMS Document": "📁",
	"AI Employee Task": "🤖",
	# Cross-app remaining (audit zero-gap)
	"Company": "🏢",
	"User": "👤",
	"Role": "🎭",
	"UOM": "📏",
	"Education Report Card": "📋",
	"Healthcare Penetration Test Report": "🔒",
	"Healthcare Load Test Report": "⚡",
	"Healthcare Diagnostic Report": "🩺",
	"Construction BIM Model Register": "🏗️",
	"Uniclass 2015 Classification": "📚",
	"Site Daily Report": "📝",
	"Construction Project Risk": "⚠️",
	"IPC Certificate": "📜",
	"Construction Hazard Register": "⚠️",
	"NCR Aging": "⏳",
	"HSE Incident Summary": "🦺",
	"Construction Executive Summary": "📊",
	"Construction EVM Dashboard": "📈",
	"IPC Certificate Summary": "📜",
	"RFQ Bid Tabulation": "📋",
	"Distribution Zone": "🗺️",
	"Trading Route Plan": "🗺️",
	"Trading Tender": "📋",
	"Trading Distribution Fulfillment": "📦",
	"Trading Route Efficiency": "🛣️",
	"Pharma Regulatory Approval": "✅",
	"Pharma Drug License": "💊",
	"Pharma Import License": "📥",
	"Pharma Export Shipment": "📤",
	"Pharma Sample Register": "🧪",
	"Pharma Import LC": "💳",
	"Temperature Excursion": "🌡️",
	"CAPA": "✅",
	"Deviation": "⚠️",
	"SOP Management": "📜",
	"Electronic Signature": "✍️",
	"Vendor Qualification": "✅",
	"Equipment Qualification": "🔧",
	"Field Plot": "🌾",
	"Vaccination Record": "💉",
	"Vehicle Damage Report": "🚗",
	"EV Charging Session": "⚡",
	"Toll Provider": "🛣️",
	"Toll Transaction": "🛣️",
	"Fleet Utilization": "🚗",
	"Fuel & Energy Cost Summary": "⛽",
	"Toll Cost Summary": "💰",
	"Education Report Card": "📑",
	"Construction Executive Summary": "📋",
	"Trading Tender": "🏷️",
	"Hospitality Audit Event": "📋",
	"Hotel Operational Asset Status": "📡",
	"Engineering Document Register": "📁",
	"PM Program": "📐",
	"PM Stakeholder Register": "👥",
	"PM Resource Assignment": "👷",
	"Risk Register": "⚠️",
	"PM CPM Groundwork": "📐",
	"PM Resource Loading": "👷",
	"PMC Management Agreement": "📜",
	"PMC Owner Statement": "🧾",
	"PMC Rent Roll": "🏠",
	"PMC Rent Aging": "⏳",
	"RE BOQ": "📋",
	"Core Classification Code": "🏷️",
	"Core Reliability by Classification": "📈",
	"Credit Engine Product": "📦",
	"Credit Engine Policy Version": "📜",
	"Consumer Finance Case": "💳",
	"Consumer Repayment Schedule": "📅",
	"Factoring Case": "📄",
	"SME Retail Finance Case": "💼",
	"Operational Risk Event": "⚠️",
	"Engineering Stage": "📐",
	"Statement of Changes in Equity": "📊",
	"Income Statement": "💰",
	"Partner Debt Statement": "🤝",
	"Decision Outcome Distribution": "📊",
	"Reason Code Distribution": "🏷️",
	"Control Effectiveness Overview": "🛡️",
}

_KEYWORD_RULES: tuple[tuple[tuple[str, ...], str], ...] = (
	(("executive", "dashboard"), "📊"),
	(("analytics", "dashboard"), "📈"),
	(("operations", "desk"), "⚙️"),
	(("finance", "desk"), "💰"),
	(("billing", "desk"), "💰"),
	(("customer", "portal"), "👤"),
	(("client", "portal"), "👤"),
	(("guest", "portal"), "🧳"),
	(("servicing", "portal"), "🎧"),
	(("sales", "portal"), "🛒"),
	(("lawyer", "desk"), "👨‍⚖️"),
	(("intake", "desk"), "📥"),
	(("paralegal",), "📋"),
	(("secretary", "desk"), "📅"),
	(("practice manager", "manager-desk"), "🏛️"),
	(("workcenter",), "🏢"),
	(("command", "center"), "🎯"),
	(("live", "tracking"), "📡"),
	(("asset", "scan"), "📱"),
	(("linen",), "🛏️"),
	(("wizard",), "🧙"),
	(("hotel", "hospitality"), "🏨"),
	(("rfid",), "📡"),
	(("acquisition",), "💵"),
	(("depreciation",), "📉"),
	(("revaluation",), "💹"),
	(("write-off", "write off"), "✂️"),
	(("disposal",), "🗑️"),
	(("transfer",), "🔄"),
	(("maintenance", "work order"), "🔧"),
	(("inspection",), "🔍"),
	(("movement", "log"), "📦"),
	(("category",), "🏷️"),
	(("location",), "📍"),
	(("fixed asset",), "🏢"),
	(("registration", "request"), "📥"),
	(("consultation",), "💬"),
	(("appointment",), "📅"),
	(("power of attorney",), "✍️"),
	(("conflict check",), "⚠️"),
	(("hearing",), "🏛️"),
	(("register", "report"), "📋"),
	(("valuation",), "💰"),
	(("forecast",), "🔮"),
	(("compliance",), "✅"),
	(("missing",), "❓"),
	(("warranty",), "⏳"),
	(("journal",), "📒"),
	(("invoice",), "🧾"),
	(("payment",), "💳"),
	(("contract",), "📜"),
	(("ticket",), "🎫"),
	(("booking", "reservation"), "📅"),
	(("patient", "clinical"), "🏥"),
	(("legal", "court", "litigation"), "⚖️"),
	(("construction", "project"), "🏗️"),
	(("manufacturing", "production", "bom"), "🏭"),
	(("inventory", "stock", "warehouse"), "📦"),
	(("employee", "payroll", "hr "), "👷"),
	(("student", "education", "school"), "🎓"),
	(("tourism", "travel", "package"), "✈️"),
	(("agriculture", "farm", "crop"), "🌾"),
	(("credit", "loan", "finance case"), "💳"),
	(("factoring",), "📄"),
	(("leasing",), "🔑"),
	(("mortgage",), "🏠"),
	(("vehicle", "car rental"), "🚗"),
	(("audit", "engagement"), "🔎"),
	(("risk", "stress"), "⚠️"),
	(("governance",), "🛡️"),
	(("e-invoice", "einvoice", "zatca", "eta", "tax"), "🧾"),
	(("document", "edms"), "📁"),
	(("ai ", "agent", "copilot"), "🤖"),
	(("pwa", "mobile"), "📱"),
	(("console",), "🖥️"),
	(("report",), "📊"),
	(("dashboard",), "📊"),
	(("portal",), "🌐"),
	(("desk",), "⚙️"),
)

_catalog_icon_cache: dict[str, dict[str, str]] = {}


def _normalize_key(value: str) -> str:
	return re.sub(r"\s+", " ", (value or "").strip().lower())


def _catalog_keys(portal: dict) -> list[str]:
	keys: list[str] = []
	for field in ("id", "page", "key"):
		val = portal.get(field)
		if val:
			keys.append(str(val))
	route = portal.get("route") or ""
	if route:
		slug = route.rstrip("/").split("/")[-1]
		if slug:
			keys.append(slug)
	return keys


def _build_catalog_icon_index(app: str) -> dict[str, str]:
	if app in _catalog_icon_cache:
		return _catalog_icon_cache[app]
	index: dict[str, str] = {}
	try:
		from omnexa_core.vertical_workcenter.default_portal_catalog import get_grouped_portal_catalog_for_app

		for group in get_grouped_portal_catalog_for_app(app, filter_by_user=False):
			for portal in group.get("portals") or []:
				icon = portal.get("icon")
				if not icon:
					continue
				for key in _catalog_keys(portal):
					index[key] = icon
					# Also index slug suffix: legal-lawyer-desk → lawyer-desk
					if "-" in key:
						parts = key.split("-", 1)
						if len(parts) == 2 and parts[0] in {
							"legal",
							"hr",
							"trading",
							"education",
							"healthcare",
							"fixed",
							"fa",
							"tourism",
							"construction",
							"finance",
							"fe",
							"cf",
							"fc",
							"rk",
							"sr",
							"sa",
							"ei",
							"svc",
							"tour",
							"eng",
							"agri",
							"rest",
							"nurs",
							"acct",
							"ce",
							"lf",
							"mg",
							"vf",
							"or",
							"mf",
							"pm",
							"rd",
							"rs",
							"mc",
						}:
							index[parts[1]] = icon
	except Exception:
		pass
	_catalog_icon_cache[app] = index
	return index


def _icon_from_default_role_portals(link_to: str) -> str | None:
	from omnexa_core.vertical_workcenter.default_portal_catalog import DEFAULT_ROLE_PORTALS

	for role in DEFAULT_ROLE_PORTALS:
		if link_to.endswith(role["key"]) and role.get("icon"):
			return role["icon"]
	return None


def _icon_from_page_suffix(link_to: str) -> str | None:
	lower = (link_to or "").lower()
	for suffix, icon in _PAGE_SUFFIX_ICONS:
		if lower.endswith(suffix):
			return icon
	return None


def _icon_from_keywords(link_to: str, label: str) -> str | None:
	haystack = _normalize_key(f"{link_to} {label}")
	for keywords, icon in _KEYWORD_RULES:
		if any(kw in haystack for kw in keywords):
			return icon
	return None


def _icon_from_tokens(link_to: str, label: str) -> str | None:
	text = _normalize_key(f"{link_to} {label}")
	for token, icon in sorted(_TOKEN_ICONS.items(), key=lambda x: -len(x[0])):
		if token in text:
			return icon
	return None


def resolve_portal_icon(
	app: str | None,
	link_type: str,
	link_to: str,
	label: str | None = None,
) -> str:
	"""Return a descriptive icon for a workspace/menu link."""
	link_to = (link_to or "").strip()
	label = (label or link_to).strip()

	if link_to in _EXACT_ICONS:
		return _EXACT_ICONS[link_to]

	if app:
		catalog = _build_catalog_icon_index(app)
		for key in (link_to, link_to.split("-", 1)[-1] if "-" in link_to else None):
			if key and key in catalog:
				return catalog[key]

	if link_type == "Page":
		for resolver in (_icon_from_page_suffix, _icon_from_default_role_portals):
			icon = resolver(link_to)
			if icon:
				return icon

	for resolver in (_icon_from_keywords, _icon_from_tokens):
		icon = resolver(link_to, label)
		if icon:
			return icon

	return _LINK_TYPE_FALLBACK.get(link_type, "•")


# Frappe desk SVG icons + accent colors for professional portal tiles.
_SVG_RULES: tuple[tuple[tuple[str, ...], str, str], ...] = (
	# Role portal pages
	(("lawyer-desk", "lawyer desk"), "es-line-filetype", "#1d4ed8"),
	(("intake-desk", "client intake"), "es-line-inbox", "#059669"),
	(("paralegal-desk", "paralegal"), "es-line-table-view", "#4f46e5"),
	(("secretary-desk", "secretary"), "es-line-calender", "#0891b2"),
	(("manager-desk", "practice manager"), "es-line-teams", "#4338ca"),
	(("executive-dashboard", "executive dashboard"), "es-line-chart", "#0f766e"),
	(("finance-desk", "billing desk"), "icon-money-coins-1", "#b45309"),
	(("analytics-dashboard", " analytics"), "es-line-chart", "#be185d"),
	(("customer-portal", "client portal desk"), "es-line-people", "#0369a1"),
	(("operations-desk", "operations desk"), "es-line-settings", "#7c3aed"),
	(("servicing-portal",), "es-line-call", "#0d9488"),
	(("sales-portal",), "es-line-tag", "#ea580c"),
	(("workcenter", "command center"), "es-line-dashboard", "#1e3a8a"),
	(("pwa", "scan", "mobile"), "es-line-web", "#7c3aed"),
	(("live-asset-tracking", "rfid", "tracking"), "es-line-location", "#0284c7"),
	(("linen",), "es-line-home", "#9333ea"),
	(("wizard",), "es-line-sparkle", "#c026d3"),
	(("hotel", "hospitality"), "es-line-home", "#db2777"),
	# Intake & CRM
	(("registration",), "es-line-inbox", "#059669"),
	(("consultation",), "es-line-chat", "#0891b2"),
	(("appointment",), "es-line-calender", "#2563eb"),
	(("power of attorney", "attorney"), "es-line-edit", "#7c3aed"),
	(("conflict",), "es-line-alert-triangle", "#dc2626"),
	# Legal / cases
	(("legal client", " clients"), "es-line-people", "#0369a1"),
	(("legal matter", "matter"), "es-line-filetype", "#1e40af"),
	(("legal case", " cases"), "es-line-filetype", "#312e81"),
	(("hearing", "court"), "es-line-status", "#4338ca"),
	(("legal task", " tasks"), "es-line-check", "#16a34a"),
	(("legal document", "document"), "es-line-attachment", "#64748b"),
	(("law firm", "lawyer profile"), "es-line-teams", "#1d4ed8"),
	(("practice area", "jurisdiction"), "es-line-tag", "#6366f1"),
	(("legal settings", "settings"), "es-line-settings", "#475569"),
	# Finance & ERP
	(("journal", "ledger"), "es-line-table-view", "#854d0e"),
	(("invoice", "receipt", "folio"), "es-line-filetype", "#b45309"),
	(("payment", "credit", "loan"), "icon-money-coins-1", "#15803d"),
	(("depreciation",), "es-line-chart", "#9333ea"),
	(("acquisition",), "icon-money-coins-1", "#047857"),
	(("supplier", "vendor"), "es-line-teams", "#78716c"),
	(("customer", "guest"), "es-line-people", "#0284c7"),
	(("inventory", "stock", "warehouse", "item"), "es-line-table-view", "#0f766e"),
	(("purchase", "sales order"), "es-line-tag", "#ea580c"),
	(("project", "engineering", "cpm", "riba"), "es-line-template", "#1e40af"),
	(("employee", "payroll", "hr ", "resource"), "es-line-people", "#0369a1"),
	(("leave", "attendance"), "es-line-calender", "#0891b2"),
	(("patient", "clinical", "healthcare"), "es-line-heart", "#e11d48"),
	(("student", "education", "report card"), "es-line-template", "#7c3aed"),
	(("construction", "bim", "hazard", "hse", "ipc"), "es-line-alert-triangle", "#c2410c"),
	(("audit", "compliance", "governance"), "es-line-check", "#0f766e"),
	(("risk", "stress", "deviation"), "es-line-alert-circle", "#dc2626"),
	(("ticket", "service"), "es-line-ticket", "#7c3aed"),
	(("booking", "reservation", "rent"), "es-line-calender", "#2563eb"),
	(("vehicle", "fleet", "car", "toll", "fuel"), "es-line-move", "#475569"),
	(("agriculture", "farm", "plot", "crop"), "es-line-image", "#65a30d"),
	(("tourism", "travel", "hotel room"), "es-line-home", "#db2777"),
	(("tax", "zatca", "e-invoice", "einvoice"), "es-line-filetype", "#0d9488"),
	(("ai ", "agent", "copilot"), "es-line-sparkle", "#8b5cf6"),
	(("document", "edms", "register"), "es-line-attachment", "#64748b"),
	(("maintenance", "inspection", "work order"), "es-line-settings", "#ca8a04"),
	(("asset", "fixed asset"), "es-line-home", "#1e3a8a"),
	(("transfer", "movement"), "es-line-move", "#0284c7"),
	(("report", "summary", "dashboard", "analytics"), "es-line-chart", "#0f766e"),
	(("company",), "es-line-home", "#475569"),
	(("branch",), "es-line-location", "#0284c7"),
	(("user", "role"), "es-line-people", "#6366f1"),
	(("fee item",), "es-line-tag", "#b45309"),
	(("billing invoice", "sales invoice", "purchase invoice"), "es-line-filetype", "#b45309"),
	(("physician", "practitioner"), "es-line-people", "#0369a1"),
	(("mobile", "pwa"), "es-line-web", "#7c3aed"),
	(("training",), "es-line-template", "#7c3aed"),
	(("validation",), "es-line-check", "#16a34a"),
	(("drug", "pharma batch", "controlled"), "es-line-tag", "#7c3aed"),
	(("cold chain", "temperature"), "es-line-alert-circle", "#0ea5e9"),
	(("import lc", "lc request"), "icon-money-coins-1", "#854d0e"),
	(("export shipment",), "es-line-arrow-up-right", "#059669"),
	(("pos", "terminal"), "es-line-tiles", "#4338ca"),
	(("distribution", "route plan"), "es-line-move", "#0284c7"),
	(("van sales",), "es-line-move", "#ea580c"),
	(("quality inspection",), "es-line-search", "#0891b2"),
	(("recall",), "es-line-alert-triangle", "#dc2626"),
	(("commercial-director",), "es-line-teams", "#4338ca"),
	(("import-manager",), "es-line-inbox", "#059669"),
	(("export-manager",), "es-line-arrow-up-right", "#059669"),
	(("cashier",), "icon-money-coins-1", "#b45309"),
	(("store-keeper", "storekeeper"), "es-line-table-view", "#0f766e"),
	(("boq",), "es-line-template", "#c2410c"),
	(("factoring case",), "es-line-filetype", "#0369a1"),
	(("portal", "console", "desk"), "es-line-web", "#6366f1"),
)

_LINK_TYPE_SVG: dict[str, tuple[str, str]] = {
	"Page": ("es-line-web", "#6366f1"),
	"DocType": ("es-line-table-view", "#475569"),
	"Report": ("es-line-chart", "#0f766e"),
	"Dashboard": ("es-line-dashboard", "#1e3a8a"),
	"Workspace": ("es-line-tiles", "#4338ca"),
	"URL": ("es-line-link", "#64748b"),
}

# Highest-priority SVG mapping by exact link_to.
_EXACT_SVG: dict[str, tuple[str, str]] = {
	# Legal pages
	"legal-workcenter": ("es-line-dashboard", "#1e3a8a"),
	"legal-lawyer-desk": ("es-line-filetype", "#1d4ed8"),
	"legal-intake-desk": ("es-line-inbox", "#059669"),
	"legal-paralegal-desk": ("es-line-table-view", "#4f46e5"),
	"legal-secretary-desk": ("es-line-calender", "#0891b2"),
	"legal-manager-desk": ("es-line-teams", "#4338ca"),
	"legal-executive-dashboard": ("es-line-chart", "#0f766e"),
	"legal-finance-desk": ("icon-money-coins-1", "#b45309"),
	"legal-analytics-dashboard": ("es-line-chart", "#be185d"),
	"legal-client-portal-desk": ("es-line-people", "#0369a1"),
	# Legal doctypes
	"Client Registration Request": ("es-line-inbox", "#059669"),
	"Legal Consultation": ("es-line-chat", "#0891b2"),
	"Legal Appointment": ("es-line-calender", "#2563eb"),
	"Legal Power of Attorney": ("es-line-edit", "#7c3aed"),
	"Legal Client": ("es-line-people", "#0369a1"),
	"Legal Matter": ("es-line-filetype", "#1e40af"),
	"Legal Case": ("es-line-filetype", "#312e81"),
	"Legal Conflict Check": ("es-line-alert-triangle", "#dc2626"),
	"Legal Hearing": ("es-line-status", "#4338ca"),
	"Legal Task": ("es-line-check", "#16a34a"),
	"Legal Document": ("es-line-attachment", "#64748b"),
	"Court": ("es-line-home", "#1e3a8a"),
	"Law Firm": ("es-line-teams", "#1d4ed8"),
	"Lawyer Profile": ("es-line-people", "#2563eb"),
	"Practice Area": ("es-line-tag", "#6366f1"),
	"Legal Jurisdiction": ("es-line-web", "#0ea5e9"),
	"Legal Branch": ("es-line-home", "#475569"),
	"Legal Office": ("es-line-home", "#334155"),
	"Legal Settings": ("es-line-settings", "#475569"),
	"Company": ("es-line-home", "#475569"),
	"Branch": ("es-line-location", "#0284c7"),
	"User": ("es-line-people", "#6366f1"),
	"Role": ("es-line-tag", "#7c3aed"),
	"CAPA": ("es-line-check", "#16a34a"),
	"Deviation": ("es-line-alert-triangle", "#dc2626"),
	"Pharma Batch": ("es-line-tag", "#7c3aed"),
	"Customer": ("es-line-people", "#0369a1"),
	"Item": ("es-line-tag", "#64748b"),
	"RE BOQ": ("es-line-template", "#c2410c"),
	"Factoring Case": ("es-line-filetype", "#0369a1"),
	"trading-commercial-director": ("es-line-teams", "#4338ca"),
	"trading-import-manager": ("es-line-inbox", "#059669"),
	"trading-export-manager": ("es-line-arrow-up-right", "#059669"),
	"trading-cashier": ("icon-money-coins-1", "#b45309"),
	"trading-store-keeper": ("es-line-table-view", "#0f766e"),
}


def _resolve_portal_icon_svg(link_type: str, link_to: str, label: str) -> tuple[str, str]:
	if link_to in _EXACT_SVG:
		return _EXACT_SVG[link_to]
	haystack = _normalize_key(f"{link_to} {label}")
	for keywords, svg, color in _SVG_RULES:
		if any(kw in haystack for kw in keywords):
			return svg, color
	return _LINK_TYPE_SVG.get(link_type, ("es-line-filetype", "#64748b"))


def resolve_portal_icon_meta(
	app: str | None,
	link_type: str,
	link_to: str,
	label: str | None = None,
) -> dict[str, str]:
	"""Emoji + Frappe SVG icon + accent color for portal menu tiles."""
	link_to = (link_to or "").strip()
	label = (label or link_to).strip()
	icon = resolve_portal_icon(app, link_type, link_to, label)
	icon_svg, icon_color = _resolve_portal_icon_svg(link_type, link_to, label)
	return {
		"icon": icon,
		"icon_svg": icon_svg,
		"icon_color": icon_color,
	}
